import { HeroLayerId, HeroLayerMap } from '@/types/hero';
import { HERO_LAYER_Z_INDEX } from '@/styles/tokens';

export const DEFAULT_HERO_LAYERS: HeroLayerMap = {
  [HeroLayerId.Layer1Atmosphere]: {
    id: HeroLayerId.Layer1Atmosphere,
    name: 'Layer 1: Background Atmosphere',
    zIndex: HERO_LAYER_Z_INDEX.layer1Atmosphere,
    interactive: false,
    parallaxFactor: 0.1,
    initialOpacity: 1,
    enabled: true,
  },
  [HeroLayerId.Layer2Environment]: {
    id: HeroLayerId.Layer2Environment,
    name: 'Layer 2: City / Environmental Background',
    zIndex: HERO_LAYER_Z_INDEX.layer2Environment,
    interactive: false,
    parallaxFactor: 0.2,
    initialOpacity: 1,
    enabled: true,
  },
  [HeroLayerId.Layer3HeroCharacter]: {
    id: HeroLayerId.Layer3HeroCharacter,
    name: 'Layer 3: Hero Character',
    zIndex: HERO_LAYER_Z_INDEX.layer3Character,
    interactive: true,
    parallaxFactor: 0.4,
    initialOpacity: 1,
    enabled: true,
  },
  [HeroLayerId.Layer4LargeTypography]: {
    id: HeroLayerId.Layer4LargeTypography,
    name: 'Layer 4: Large Typography',
    zIndex: HERO_LAYER_Z_INDEX.layer4Typography,
    interactive: false,
    parallaxFactor: 0.5,
    initialOpacity: 1,
    enabled: true,
  },
  [HeroLayerId.Layer5ParticlesWeb]: {
    id: HeroLayerId.Layer5ParticlesWeb,
    name: 'Layer 5: Web / Particle Effects',
    zIndex: HERO_LAYER_Z_INDEX.layer5Particles,
    interactive: false, // particles/web lines need no pointer events — let them pass to Layer 3
    parallaxFactor: 0.6,
    initialOpacity: 1,
    enabled: true,
  },
  [HeroLayerId.Layer6MaskTransition]: {
    id: HeroLayerId.Layer6MaskTransition,
    name: 'Layer 6: Mask / Face Transition',
    zIndex: HERO_LAYER_Z_INDEX.layer6MaskTransition,
    interactive: false,
    parallaxFactor: 0.8,
    initialOpacity: 0,
    enabled: true,
  },
  [HeroLayerId.Layer7AhmedFace]: {
    id: HeroLayerId.Layer7AhmedFace,
    name: 'Layer 7: Ahmed Face Layer',
    zIndex: HERO_LAYER_Z_INDEX.layer7AhmedFace,
    interactive: false,
    parallaxFactor: 0.9,
    initialOpacity: 0,
    enabled: true,
  },
  [HeroLayerId.Layer8ForegroundEffects]: {
    id: HeroLayerId.Layer8ForegroundEffects,
    name: 'Layer 8: Foreground Effects',
    zIndex: HERO_LAYER_Z_INDEX.layer8ForegroundEffects,
    interactive: false,
    parallaxFactor: 1.0,
    initialOpacity: 1,
    enabled: true,
  },
};
